"""empty message

Revision ID: 5549eee87c2f
Revises: 57d717c69e8d
Create Date: 2023-06-02 11:44:46.559048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5549eee87c2f'
down_revision = '57d717c69e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('room_owner')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_owner', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
